# Change these first
owner: davorg # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Line of Succession
    url: https://lineofsuccession.co.uk/
  - name: Dave Cross
    url: https://davecross.co.uk/
  - name: dave.org.uk
    url: https://dave.org.uk/
  - name: Davblog
    url: https://blog.dave.org.uk/
  - name: Perl Hacks
    url: https://perlhacks.com/
  - name: Feeds
    url: https://feeds.davecross.co.uk/
  - name: Lystyng
    url: https://lystyng.com/
  - name: Melody
    url: https://melody.red-mirror.com/
  - name: Perl Diver Auth
    url: https://pdauth.perlhacks.com/
  - name: AdServer
    url: https://ads.davecross.co.uk/
  - name: Klortho
    url: https://klortho.perlhacks.com/
  - name: Aphra
    https://aphra.perlhacks.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime monitoring for Dave's sites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
